### ISSUE TITLE
Feedback and Inquiry About Frontlines Support

### ISSUE THREAD

**Issue by Leirsgrios** [wrath16/PvpStats#1]
I first wanted to say that this is an amazing effort and I am so glad you've put in the work on this. I've long wanted a way to keep track of this information given FFXIV's lack of real stats tracking, and I have to say thank you!

Do you have any idea of how long it might be before Frontlines functionality is integrated? I am really excited for that and just have to ask.

**Comment by wrath16** [comment]
Sometime before 7.0 likely. Can't say for certain since I haven't started looking at Frontline yet so I don't know how complicated it'll be.

**Comment by Leirsgrios** [comment]
Hey wrath, thank you for the Frontlines addition! Is it feasible to add cumulative individual stats? Like average dmg/kills/dmg taken/healing and maybe like average kill/dmg/heal ranking per game?

**Comment by wrath16** [comment]
Average Frontline stats in the Summary tab is available with the latest update.

**Comment by Leirsgrios** [comment]
I only see stats for the win/loss ratio, I don't see anything about the
individual performance like damage output, kills, etc.

**Comment by wrath16** [comment]
Enable testing builds. v2.0.2.1 is the latest testing build.

**Comment by Leirsgrios** [comment]
Got it! Thank you! Awesome work!
