### ISSUE TITLE
Suggestion: New Chat commands to open most recent match

### ISSUE THREAD

**Issue by TheKedart** [wrath16/PvpStats#2]
I would love to have a chat command such as `/ccstats last` or `/ccstats recent` (for any/all game modes the plugin supports) which opens the most recent match results. 90% of the time I open the plugin interface it is just to click the most recent match anyway; this could save some clicks and menuing.

**Comment by wrath16** [comment]
Checkout the `/lastmatch` command implemented in v.2.1.9.0.

**Comment by TheKedart** [comment]
Fantastic, this is exactly what I wanted. Thank you!
